"""
Agent Models

Defines the internal communication models used by the
AI Analytics Agent.

Project: AI Analytics Copilot
Author: Sangeeth S
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ==========================================================
# Agent Intent
# ==========================================================

class AgentIntent(str, Enum):
    """
    High-level intent detected from the user's request.
    """

    ANALYSIS = "analysis"
    VISUALIZATION = "visualization"
    RECOMMENDATION = "recommendation"
    REPORT = "report"
    GENERAL = "general"


# ==========================================================
# Tool Type
# ==========================================================

class ToolType(str, Enum):
    """
    Supported tools inside the Analytics Agent.
    """

    DATASET = "dataset"
    ANALYSIS = "analysis"
    VISUALIZATION = "visualization"
    RECOMMENDATION = "recommendation"
    REPORT = "report"


# ==========================================================
# Tool Request
# ==========================================================

class ToolRequest(BaseModel):
    """
    Request sent to a tool.
    """

    tool: ToolType = Field(
        ...,
        description="Tool that should execute the request."
    )

    action: str = Field(
        ...,
        description="Action the tool should perform."
    )

    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Input parameters for the tool."
    )

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# Execution Step
# ==========================================================

class ExecutionStep(BaseModel):
    """
    Represents a single step in the execution graph.
    """

    step_number: int = Field(
        ...,
        ge=1,
    )

    description: str = Field(
        ...,
        min_length=1,
    )

    tool_request: ToolRequest

    depends_on: list[int] = Field(
        default_factory=list,
        description="Previous steps required before execution."
    )

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# Execution Graph
# ==========================================================

class ExecutionGraph(BaseModel):
    """
    Ordered execution plan.
    """

    steps: list[ExecutionStep]

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# Agent Plan
# ==========================================================

class AgentPlan(BaseModel):
    """
    Complete execution plan generated by the planner.
    """

    intent: AgentIntent

    execution_graph: ExecutionGraph

    requires_llm: bool = True

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# Tool Metadata
# ==========================================================

class ToolMetadata(BaseModel):
    """
    Metadata produced after tool execution.
    """

    execution_time: float = Field(
        ...,
        ge=0,
        description="Execution time in seconds."
    )

    executed_at: datetime = Field(
        default_factory=datetime.utcnow,
    )

    tool_version: str = Field(
        default="1.0.0",
    )

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# Tool Result
# ==========================================================

class ToolResult(BaseModel):
    """
    Standard response returned by every tool.
    """

    tool: ToolType

    success: bool

    message: str

    payload: dict[str, Any] = Field(
        default_factory=dict,
    )

    metadata: ToolMetadata

    error: str | None = None

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# Agent Context
# ==========================================================

class AgentContext(BaseModel):
    """
    Structured context passed to the prompt composer.
    """

    dataset_info: dict[str, Any] = Field(
        default_factory=dict,
    )

    analysis: dict[str, Any] = Field(
        default_factory=dict,
    )

    available_columns: dict[str, Any] = Field(
        default_factory=dict,
    )

    sample_rows: list[dict[str, Any]] = Field(
        default_factory=list,
    )

    tool_results: list[ToolResult] = Field(
        default_factory=list,
    )

    user_question: str

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# LLM Request
# ==========================================================

class LLMRequest(BaseModel):
    """
    Request sent to an LLM provider.
    """

    system_prompt: str

    user_prompt: str

    temperature: float = Field(
        default=0.2,
        ge=0.0,
        le=2.0,
    )

    max_tokens: int = Field(
        default=1000,
        ge=1,
    )

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# LLM Response
# ==========================================================

class LLMResponse(BaseModel):
    """
    Response returned by an LLM provider.
    """

    content: str

    model_name: str

    provider: str

    tokens_used: int | None = None

    finish_reason: str | None = None

    model_config = {
        "extra": "forbid",
        "frozen": True,
    }


# ==========================================================
# Agent Response
# ==========================================================
class AgentResponse(BaseModel):

    success: bool

    answer: str

    intent: AgentIntent | None = None

    plan: AgentPlan | None = None

    context: AgentContext | None = None

    tool_results: list[ToolResult] = Field(
        default_factory=list
    )

    llm_response: LLMResponse | None = None