"""
Agent Models

Defines the internal communication models used by the
AI Analytics Agent.

Project: AI Analytics Copilot
Author: Sangeeth S
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Any

import pandas as pd

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
)

from app.schemas.analysis import DatasetAnalysis


# ==========================================================
# Agent Intent
# ==========================================================

class AgentIntent(str, Enum):
    """
    High-level intent detected from the user's request.
    """

    ANALYSIS = "analysis"

    VISUALIZATION = "visualization"

    RECOMMENDATION = "recommendation"

    REPORT = "report"

    GENERAL = "general"


# ==========================================================
# Tool Type
# ==========================================================

class ToolType(str, Enum):
    """
    Supported AI Agent tools.
    """

    DATASET = "dataset"

    ANALYSIS = "analysis"

    VISUALIZATION = "visualization"

    RECOMMENDATION = "recommendation"

    REPORT = "report"


# ==========================================================
# Tool Request
# ==========================================================

class ToolRequest(BaseModel):
    """
    Request sent to a tool.
    """

    tool: ToolType = Field(
        ...,
        description="Tool that should execute the request.",
    )

    action: str = Field(
        ...,
        description="Action the tool should perform.",
    )

    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Input parameters for the tool.",
    )

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )


# ==========================================================
# Execution Step
# ==========================================================

class ExecutionStep(BaseModel):
    """
    Represents a single execution step.
    """

    step_number: int = Field(
        ...,
        ge=1,
    )

    description: str = Field(
        ...,
        min_length=1,
    )

    tool_request: ToolRequest

    depends_on: list[int] = Field(
        default_factory=list,
        description="Previous steps required before execution.",
    )

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )


# ==========================================================
# Execution Graph
# ==========================================================

class ExecutionGraph(BaseModel):
    """
    Ordered execution graph.
    """

    steps: list[ExecutionStep]

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )


# ==========================================================
# Agent Plan
# ==========================================================

class AgentPlan(BaseModel):
    """
    Complete execution plan generated by the planner.
    """

    intent: AgentIntent

    execution_graph: ExecutionGraph

    requires_llm: bool = True

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )

# ==========================================================
# Tool Metadata
# ==========================================================

class ToolMetadata(BaseModel):
    """
    Metadata produced after tool execution.
    """

    execution_time: float = Field(
        ...,
        ge=0,
        description="Execution time in seconds.",
    )

    executed_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
    )

    tool_version: str = Field(
        default="1.0.0",
        description="Version of the executed tool.",
    )

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )


# ==========================================================
# Tool Result
# ==========================================================

class ToolResult(BaseModel):
    """
    Standard response returned by every tool.
    """

    tool: ToolType = Field(
        ...,
        description="Tool that produced the result.",
    )

    success: bool = Field(
        ...,
        description="Whether execution succeeded.",
    )

    message: str = Field(
        ...,
        description="Human-readable execution message.",
    )

    payload: Any = Field(
        default=None,
        description="Tool-specific response payload.",
    )

    metadata: ToolMetadata

    warnings: list[str] = Field(
        default_factory=list,
        description="Non-fatal warnings generated during execution.",
    )

    error: str | None = Field(
        default=None,
        description="Error message if execution failed.",
    )

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )


# ==========================================================
# Agent Context
# ==========================================================

class AgentContext(BaseModel):
    """
    Structured context passed to the Prompt Composer.
    """

    dataset_info: dict[str, Any] = Field(
        default_factory=dict,
    )

    analysis: dict[str, Any] = Field(
        default_factory=dict,
    )

    available_columns: dict[str, Any] = Field(
        default_factory=dict,
    )

    sample_rows: list[dict[str, Any]] = Field(
        default_factory=list,
    )

    tool_results: list[ToolResult] = Field(
        default_factory=list,
    )

    user_question: str

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )
# ==========================================================
# LLM Request
# ==========================================================

class LLMRequest(BaseModel):
    """
    Request sent to an LLM provider.
    """

    system_prompt: str = Field(
        ...,
        description="System prompt.",
    )

    user_prompt: str = Field(
        ...,
        description="User prompt.",
    )

    temperature: float = Field(
        default=0.2,
        ge=0.0,
        le=2.0,
    )

    max_tokens: int = Field(
        default=1000,
        ge=1,
    )

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )


# ==========================================================
# LLM Response
# ==========================================================

class LLMResponse(BaseModel):
    """
    Response returned by an LLM provider.
    """

    content: str = Field(
        ...,
        description="Generated response.",
    )

    model_name: str = Field(
        ...,
        description="Model used.",
    )

    provider: str = Field(
        ...,
        description="Provider name.",
    )

    tokens_used: int | None = Field(
        default=None,
        description="Total tokens consumed.",
    )

    finish_reason: str | None = Field(
        default=None,
        description="Completion finish reason.",
    )

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )


# ==========================================================
# Agent Response
# ==========================================================

class AgentResponse(BaseModel):
    """
    Final response returned by the AI Agent.
    """

    success: bool = Field(
        ...,
        description="Whether execution succeeded.",
    )

    answer: str = Field(
        ...,
        description="Final response generated for the user.",
    )

    intent: AgentIntent | None = Field(
        default=None,
    )

    plan: AgentPlan | None = Field(
        default=None,
    )

    context: AgentContext | None = Field(
        default=None,
    )

    tool_results: list[ToolResult] = Field(
        default_factory=list,
    )

    llm_response: LLMResponse | None = Field(
        default=None,
    )

    model_config = ConfigDict(
        extra="forbid",
        frozen=True,
    )


# ==========================================================
# Tool Execution Context
# ==========================================================

class ToolExecutionContext(BaseModel):
    """
    Runtime context passed to every tool.
    """

    dataset_id: str = Field(
        ...,
        description="Unique dataset identifier.",
    )

    dataframe: pd.DataFrame

    analysis: DatasetAnalysis | None = Field(
        default=None,
        description="Cached dataset analysis.",
    )

    question: str = Field(
        ...,
        description="Original user question.",
    )

    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        extra="forbid",
    )    